Months = set(["January", "February", "March", "April", "May", "June"])
print("\nprinting the original set ... ")
print(Months)
print("\nupdating the original set ... ")
Months.update(["July", "August", "September", "October"])
print("\nprinting the modified set ... ")
print(Months)
print("Adding multiple values")
Months.update([4, 5], {1, 6, 8})
print(Months)